# Generated by Django 3.2.8 on 2021-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('has_more', models.BooleanField()),
                ('backoff', models.CharField(max_length=5)),
                ('quota_max', models.CharField(max_length=300)),
                ('quota_remaining', models.CharField(max_length=500)),
            ],
        ),
    ]
